---
- name: Deploy app to raspberry pi
  hosts: pi
  remote_user: pi
  gather_facts: false
  vars:
    repository: https://github.com/theoperatore/andrew-bot-discord.git

  tasks:
    - name: App | clone latest
      git:
        repo: '{{ repository }}'
        dest: /alorg/app
      register: git_finished

    - name: App | install dependencies
      shell: yarn install --frozen-lockfile --network-timeout 300000
      register: yarn_finished
      failed_when: '"error" in yarn_finished.stderr'
      when: git_finished.changed
      args:
        chdir: /alorg/app

    - name: App | build
      shell: yarn build
      when: git_finished.changed
      args:
        chdir: /alorg/app

    - name: App | stop
      shel: yarn stop
      args:
        chdir: /alorg/app
      ignore_errors: yes
      when: git_finished.changed

    - name: App | start
      shell: yarn start
      args:
        chdir: /alorg
      when: git_finished.changed
