#!/bin/bash

# These come from https://docs.docker.com/docker-cloud/builds/advanced/
docker build --build-arg=COMMIT=SOURCE_COMMIT --build-arg=BRANCH=$SOURCE_BRANCH -f $DOCKERFILE_PATH -t $IMAGE_NAME .
